### ISSUE TITLE
Colorful Console Log

### ISSUE THREAD

**Issue by PoH98** [KonataDev/Konata#67]
Sorry for disturbing but I think there is already a colorful console logger which can be used at this [link](https://github.com/tomakita/Colorful.Console). Hope can get some help on this project!

**Comment by TheSnowfield** [comment]
Thank you very much!! ❤ But I am very busy in these days.
BTW, This project need your help! Would you like to join us?  😊

**Comment by PoH98** [comment]
A bit hard, but I'll keep watching the project, I'm busy too ;)

**Comment by TheSnowfield** [comment]
> A bit hard, but I'll keep watching the project, I'm busy too ;)

Okay. If you want, we're welcome! 😊
